### ISSUE TITLE
Upload machine learning data into youcat

### ISSUE THREAD

**Issue by andamian** [opencadc/notebook-ui#4]
1. Create schema file (VOSITable format). See http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/argus/tables/caom2.Observation as example.
2. Create table with cadc-tap. Might need to use Hossein's certificate.
3. Upload content.

**Comment by LiaoWenyun** [comment]
Task done.
Table was created in schema ml.
Table name: Image_Quality_Table;
Columns: Image_ID(string), Good_Probability(double), Really_Bad_Tracking(double), Bad_Tracking(double), Bad_Weather(double), A_Problem_in_Background(double), Number_of_Dead_CCDs(int);

**Comment by andamian** [comment]
@hossteim What do you think about this name convention for the table? What is `reallyBadTracking`? Can it be replaced with something that makes more sense?

MegaprimeQuality

observationID
quality
reallyBadTracking
badTracking
badWeather
brackgroundNoise
deadCCDs

**Comment by hossteim** [comment]
I think quality should be goodQuality

also brackgroundNoise should be brackgroundProblem

reallyBadTracking is the name that Stephen has chosen

**Comment by andamian** [comment]
OK with backgroundProblem and reallyBadTracking.

I don't understand why goodQuality but we can go with it if it makes sense to you.

**Comment by andamian** [comment]
@LiaoWenyun - we've agreed with @hossteim to use the following names:

MegaprimeQuality
=============
observationID
overallQuality
reallyBadTracking
badTracking
badWeather
brackgroundProblem
deadCCDs

**Comment by LiaoWenyun** [comment]
@andamian @hossteim 
Task done, please check.

Created Table MegaprimeQuality in schema ml;
-Created column: observationID, type: string;
-Created column: overallQuality, type: double
-Created column: reallyBadTracking: double
-Created column: badTracking, type: double
-Created column: badWeather, type: double
-Created column: brackgroundProblem, type: double
-Created column: deadCCDs, type: int
Added table access permission: others can read

**Comment by LiaoWenyun** [comment]
@andamian @hossteim 
Task done, please check.

Created Table MegaprimeQuality in schema ml;
-Created column: observationID, type: string;
-Created column: overallQuality, type: double
-Created column: reallyBadTracking: double
-Created column: badTracking, type: double
-Created column: badWeather, type: double
-Created column: brackgroundProblem, type: double
-Created column: deadCCDs, type: int
Added table access permission: others can read
